version: '3.3'

services:
  plesk:
    image: plesk/plesk
    command: ["/bin/bash"]
    volumes:
      - /${APP_DATA_DIR}/sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "80:80"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
      environment:
       APP_HOST: cloudrack-plesk_1
       APP_PORT: 8880
       TITLE: cloudrack-plesk
    ports:
      - '8540:80'
      - '4463:443'
      - '8880:8880'
      - '8443:8443'
      - '8447:8447'
      - '3332:21'
      - '3844:3306'
    volumes:
      - /${APP_DATA_DIR}/sys/fs/cgroup:/sys/fs/cgroup:ro
